pipeline {
    agent {
        docker {
            image 'maven:3.9.6-eclipse-temurin-17'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
    }
    }
    stages {
        stage('Build') { // Build code
            steps {
                sh 'cd java-spring-boot && mvn clean package -DskipTests'
            }
        }

        stage('Unit test') { // Unit test
            steps {
                sh 'echo "Test"'
                //sh 'mvn test'
            }
        }
        
        /*stage('Sonar') { // SAST with Sonar
            environment {
                SONAR_URL = "http://IP:9000"
            }
            steps {
                withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                    //sh 'cd java-spring-boot && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
                }
            }
        }  */

        stage('Push to Artifactory') { // Push jar artifact to Artifactory
            steps {
                sh 'echo "Push to nexus"'
            }
        }

        stage('Docker Image') { // Build Docker Image
            steps {
                sh 'apt-get update && apt-get install -y docker.io'
                sh 'cd java-spring-boot && docker build -t kevinjoehar/end-to-end-jenkins:${BUILD_NUMBER} .'
            }
        }

        stage('Trivy') { // Image vulnerability test
            steps {
                sh 'echo "Trivy Scan"'
            }
        }

        stage('Push to Registry') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', 
                                usernameVariable: 'DOCKER_USER', 
                                passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin"
                    sh "docker push kevinjoehar/end-to-end-jenkins:${BUILD_NUMBER}"
                }
            }
        }

        stage('Update K8 Image Tag') { // The 'Deploy' stage
            environment {
                GIT_REPO_NAME = "end-to-end-jenkins"
                GIT_USER_NAME = "Kevinjoeharris"
            }
            steps {
                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                        git config user.email "kevinjoeharris1@gmail.com"
                        git config user.name "Kevinjoeharris"
                        BUILD_NUMBER=${BUILD_NUMBER}
                        sed -i "s|end-to-end-jenkins:.*|end-to-end-jenkins:${BUILD_NUMBER}|g" end-to-end-jenkins/manifests/deployment.yaml
                        git commit -am "ci: bump image to ${BUILD_NUMBER}"
                        git push
                    '''
            }
        }
     }
    }

    
    post { // Actions to run after the pipeline finishes
        always { // Runs regardless of the pipeline outcome
            echo 'Pipeline finished.'
            junit 'target/surefire-reports/*.xml'
        }
        failure { // Runs only if the pipeline fails
            echo 'Pipeline failed!'
            }
        }
    
}
