apiVersion: apps/v1
kind: Deployment
metadata:
  name: end-to-end-jenkins
  labels:
    app: spring-boot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - name: spring-boot-container
        image: kevinjoehar/end-to-end-jenkins:latest
